// Catálogo de productos (offline, sin APIs externas)
export const products = [
  {
    id: 'P001',
    name: 'Auriculares Bluetooth ProSound X1',
    category: 'Audio',
    price: 159.9,
    oldPrice: 219.9,
    rating: 4.6,
    stock: 14,
    thumb: '🎧',
  },
  {
    id: 'P002',
    name: 'Smartwatch FitPlus Active 3',
    category: 'Wearables',
    price: 349.0,
    oldPrice: null,
    rating: 4.3,
    stock: 7,
    thumb: '⌚',
  },
  {
    id: 'P003',
    name: 'Teclado mecánico RGB K-75',
    category: 'Periféricos',
    price: 89.5,
    oldPrice: 129.0,
    rating: 4.7,
    stock: 22,
    thumb: '⌨️',
  },
  {
    id: 'P004',
    name: 'Cámara web HD StudioCam 1080',
    category: 'Periféricos',
    price: 64.9,
    oldPrice: null,
    rating: 4.1,
    stock: 3,
    thumb: '📷',
  },
  {
    id: 'P005',
    name: 'Mochila urbana TechCarry 22L',
    category: 'Accesorios',
    price: 49.9,
    oldPrice: 69.0,
    rating: 4.5,
    stock: 35,
    thumb: '🎒',
  },
  {
    id: 'P006',
    name: 'Mouse ergonómico ErgoMouse Vertical',
    category: 'Periféricos',
    price: 39.9,
    oldPrice: null,
    rating: 4.4,
    stock: 18,
    thumb: '🖱️',
  },
  {
    id: 'P007',
    name: 'Lámpara LED SmartGlow con WiFi',
    category: 'Hogar',
    price: 28.5,
    oldPrice: null,
    rating: 4.0,
    stock: 50,
    thumb: '💡',
  },
  {
    id: 'P008',
    name: 'Cargador rápido GaN 65W',
    category: 'Accesorios',
    price: 32.0,
    oldPrice: 44.0,
    rating: 4.6,
    stock: 27,
    thumb: '🔌',
  },
  {
    id: 'P009',
    name: 'Parlante portátil AquaSound Mini',
    category: 'Audio',
    price: 79.0,
    oldPrice: null,
    rating: 4.2,
    stock: 11,
    thumb: '🔊',
  },
];

export const categories = ['Todas', 'Audio', 'Wearables', 'Periféricos', 'Accesorios', 'Hogar'];
export const priceRanges = ['Cualquier precio', 'Menos de S/ 50', 'S/ 50 - S/ 100', 'S/ 100 - S/ 200', 'Más de S/ 200'];
